git:
  depth: 1
env:
  global:
  - AWS_DEFAULT_REGION: us-west-1
  - S3_PARAMS: '"--acl public-read --cache-control \"public,must-revalidate,proxy-revalidate,max-age=0\""'
  - secure: Vh+9Z2qvfJXXXa0+8Jn6bJtB7wmojaiGAiOiPFVsLheYh0Vkab0fhN+3zkM/H82p8raYLANJdwzwcsBOcLpU923HFH+M1PMR4IrS6neYPdeSrh4thLXtzlmi5nkwOyjIZw3sALyl+JZ8a57STfCjG/WhOm0/Hm4JTC7hFfno2xvuMmITlZE47v02UmZUxCNmnH8tsnvJoBkWPc2nnkIXhRatAh1X0jI8RlI4pchh99wE8biWNPsQD6Tzw/ml5WOOO2LxvsqGmmv3mYIUtSOvEa4l2s5Z7lss7AU6G+ZHzt6Ed8UyQMhaI6GSVSGUJFtuCDFUoJ10v6fvPfnDcx9MaWjMC1FhIsrtMXz/+wpSVIP9wJryZPuW1sP/gG3r+7MGQZ++tnW0arjMrCXOYi/yL194UbEodv/zkkxuWndWv3FRT+eYqtXomKE5sp3JervnJ1wGqyNYebExU6TiNlhUuRotJ2QB6srkosdWKOIZPSNNND5byfzhedNw4KmZiCa5ILndR96bDcU3x4FubKYYPp/oqoUM9sNSWXyy3yu9qXUwf6CBKD7r+7R/EImUDDlZSvb28L8SG8OFTFxQ5EQP+UG2ho2a3EDCeO4v+9MN3iaDnDykiekODC5DWxMRWh/hgc/ahvQY7+tOIizIpFqsEpK+cnLCnmv507woAnkk/w8=
  - secure: NnAzCxO650RziroI44+m1DjGTOCjXVtfgC03216SYSSyV0/xFoFHx4UZt/KXD3pQVmM+kWGx1zpG0ltB4q3H1CkUMadzFfQuNzaVOWnmhy7oNR9i9/DW2i6Oz86XlDf/wC7ySYpc4AVftD1GSudVAzjBGYi/ragY/GSdCEBUSFP61yfhhrN3bsbYkFF/sfPMoW7WLWnwQoUOdZhD79LZqpMxMlipqZSbwzaYIuNiS/8IJAmkUQPdl9YQdDGEcuVaRWZilOPju/5UUXgQmYwjhViJpzM/SmvDj8FgWa+Sw5wR5fzVNrq4Hj0/7bC2dzTpMl4cqXnQjFxYzPwWZVPKO+E1tPtbFJPiNSPUguii37f2gt1KtBQugiT4ASS1D3oocruqTZOMX/IouJRUZGagSEqj2QpXnKiH2Xq478lL1fV2bXQjJWXo16EBt2lYYj7ibXSzsUmG9Dh1X5mWcPlvHlqsOB/ZCxMzpluVRqWNl+Tn3gVsD/bjhKY7kZ+BaoFAnUXg9CoHybMI42rmxvPLNqCpmSpP7jQtxMhMe076u2WXJ7/M71rq300wDxT8Ug03cUDRzeaMC8jzzuz7NYm5Ft5TOKcON+ybsdnIfnVkjs3eQJo5JAwr2xJ3TfcpZyTZN3ORlPamHvce0OA0noj0SRwtwBSpGSOVWc/tS9LR61g=
matrix:
  include:
  - name: Linux x64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - mkdir build
    - cd build
    - CC="gcc-4.8" cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - aws s3 cp dyncall/libdyncall_s.a s3://lwjgl-mips64/nightly/linux/x64/core/
      $S3_PARAMS
    - aws s3 cp dyncallback/libdyncallback_s.a s3://lwjgl-mips64/nightly/linux/x64/core/
      $S3_PARAMS
    - aws s3 cp dynload/libdynload_s.a s3://lwjgl-mips64/nightly/linux/x64/core/
      $S3_PARAMS
  - name: Linux arm32
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8-arm-linux-gnueabihf
        - libc6-dev-armhf-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - mkdir build
    - cd build
    - CC="arm-linux-gnueabihf-gcc-4.8" cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - aws s3 cp dyncall/libdyncall_s.a s3://lwjgl-mips64/nightly/linux/arm32/core/
      $S3_PARAMS
    - aws s3 cp dyncallback/libdyncallback_s.a s3://lwjgl-mips64/nightly/linux/arm32/core/
      $S3_PARAMS
    - aws s3 cp dynload/libdynload_s.a s3://lwjgl-mips64/nightly/linux/arm32/core/
      $S3_PARAMS
  - name: Linux arm64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-4.8-aarch64-linux-gnu
        - libc6-dev-arm64-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - mkdir build
    - cd build
    - CC="aarch64-linux-gnu-gcc-4.8" cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - aws s3 cp dyncall/libdyncall_s.a s3://lwjgl-mips64/nightly/linux/arm64/core/
      $S3_PARAMS
    - aws s3 cp dyncallback/libdyncallback_s.a s3://lwjgl-mips64/nightly/linux/arm64/core/
      $S3_PARAMS
    - aws s3 cp dynload/libdynload_s.a s3://lwjgl-mips64/nightly/linux/arm64/core/
      $S3_PARAMS
  - name: Linux mips64
    dist: xenial
    language: c
    compiler: gcc
    addons:
      apt:
        packages:
        - cmake
        - gcc-5-mips64el-linux-gnuabi64
        - g++-5-mips64el-linux-gnuabi64
        - libc6-dev-mips64el-cross
    before_install:
    - pip install --user awscli
    - export PATH=$PATH:$HOME/.local/bin
    script:
    - mkdir build
    - cd build
    - CC="mips64el-linux-gnuabi64-gcc-5" cmake -DCMAKE_BUILD_TYPE=Release ..
    - cmake --build .
    - aws s3 cp dyncall/libdyncall_s.a s3://lwjgl-mips64/nightly/linux/mips64/core/
      $S3_PARAMS
    - aws s3 cp dyncallback/libdyncallback_s.a s3://lwjgl-mips64/nightly/linux/mips64/core/
      $S3_PARAMS
    - aws s3 cp dynload/libdynload_s.a s3://lwjgl-mips64/nightly/linux/mips64/core/
      $S3_PARAMS
  - name: macOS
    language: objective-c
    osx_image: xcode11.3
    compiler: clang
    before_install:
    - brew update
    install:
    - brew install awscli
    script:
    - mkdir build
    - cd build
    - cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_OSX_DEPLOYMENT_TARGET=10.9 ..
    - cmake --build .
    - aws s3 cp dyncall/libdyncall_s.a s3://lwjgl-mips64/nightly/macosx/x64/core/
      $S3_PARAMS
    - aws s3 cp dyncallback/libdyncallback_s.a s3://lwjgl-mips64/nightly/macosx/x64/core/
      $S3_PARAMS
    - aws s3 cp dynload/libdynload_s.a s3://lwjgl-mips64/nightly/macosx/x64/core/
      $S3_PARAMS
